source:
  - changed-files:
      - any-glob-to-any-file: 'src/**'

tests:
  - changed-files:
      - any-glob-to-any-file: 'test/**'

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'README.md'
          - 'CHANGELOG.md'
          - 'CONTRIBUTING.md'
          - 'SECURITY.md'
          - 'CODE_OF_CONDUCT.md'
